### ISSUE TITLE
Can't create USB stick for backup/jailbreak

### ISSUE THREAD

**Issue by fabiocattaneo** [emuchicken/pandorytool#27]
I've extracted the pandory release 1.07 zip file, formatted a 64GB USB stick using exFAT, 32k filesystem. Opened the terminal as administrator and typed pandory stick backup e:/
Chosen "1" then pressed  enter.
Error: unable to create directory e:\
Tried again with different USB stick, no luck.
Switched from Windows 7 to Windows 10, on a different PC.
Same results.

**Comment by Brainfodder** [comment]
Try E:\ instead on the end of the command line instead of E:/ is the only thing I can think of causing that.

**Comment by emuchicken** [comment]
I always leave it as
pandory stick backup e:

Did you verify that your usb stick is good via a fake tester?

**Comment by fabiocattaneo** [comment]
Yes, I did both things with no luck...

**Comment by emuchicken** [comment]
Can you come down to our discord?

**Comment by fluxit1** [comment]
I had this issue on Windows 7 with the backup and jailbreak.  To work around it I created a temp directory on my usb stick and had pandory tool do it's preparations in that directory, then moved them to "/" of the usb stick manually.

Strangely though, "pandory add" was able to write to the root directory the first time I used it, but later on my mcgames directory disappeared(I probably accidentally deleted it,) and the next "add" resulted in another "error: unable to create directory."  Things went smoothly again after I manually recreated mcgames on the stick.

As far as pandory was concerned, it didn't matter if I tried to use "d:/" "d:\" "d:" "D:" "D:/" or "D:\" to refer to the usb stick though, pandory wasn't having it and would throw the same error.

**Comment by dajoho** [comment]
@fabiocattaneo did you ever fix this?

**Comment by fabiocattaneo** [comment]
> @fabiocattaneo did you ever fix this?

No, I gave up

**Comment by dajoho** [comment]
@fabiocattaneo 

This seems to be an issue with certain security software. Do it a different way:

1. format a fresh usb stick in exfat format (I use the software "Rufus")
2. open the command prompt, switch to the pandory folder but do something different create a folder first like this:
3. `mkdir foo`
4. then, run:  `pandory stick backup foo`
5. pandory should copy all the relevant files into the `foo` folder instead of to your USB stick.
6. copy the files from the `foo` folder to your usb stick manually.
