### ISSUE TITLE
Integration with Pixelcade Dynamic Marquees Idea

### ISSUE THREAD

**Issue by alinke** [emuchicken/pandorytool#38]
Hey there, this isn't an issue but rather an ask. I am the creator of the Pixelcade line of dynamic marquees that change to match the selected game, see http://pixelcade.org. I have a few customers with Pandora boxes who have asked if there is a way to get Pandora to work with Pixelcade. A couple things would need to happen:

1. I would need to port the current Java based Pixelcade application to Android. This would take some time but is doable. 
2. The Pixelcade program (aka Pixelcade Listener) runs in the background and listens for incoming REST calls to localhost:8080 . So Pandory / Pandora would need to send a REST API call like for example each time the user scrolls or launches a new game: http://localhost:8080/arcade/stream/mame/pacman , the Pixelcade REST API is documented here http://pixelcade.org/api for reference. 

Not sure how feasible this would be but just thought to check. If this collaboration is of interest, shoot me a note at al@ledpixelart.com and can go from there. And I would be willing to fund it as well. Thanks much, Al

**Comment by dajoho** [comment]
Hey there,

That's an interesting idea!

This might be doable on the Moorechip-based Pandora Android models (9h, 3d, 3d+, 3D Saga, 18S etc), although I think the operator API is already listening on 8080. 

A curl request would be relatively easy to do from pandory I think - we could just monitor the system-logs to see when games are started and then ping the operator API to get the rom name and then forward it to the REST service.

But; you would have to port your java app to C/C++ using the android NDK instead of using the normal SDK, as android apps run one at once and aren't usually to run as services. It's doable though.

Alternatively, all moorechip consoles support USB-ethernet. You could route the pandora to a Raspberry pi and let that do the work of driving your marquee panel.


HOWEVER! Many arcade enthusiasts swear blind that the linux-based DX and CX consoles are the best (as they are the 'official' Pandoras). This is unfortunately not the case and they have a very restrictive kernel with limited networking support. It may be very hard to port your service to these consoles as they are incredibly low powered (honestly- it's a wonder they even boot up to be truthful!)

So you would have to gauge what your customers are asking for- if they are all on the DX/CX trip, basically forget it. If you have a lot of people using the moorechip consoles, the answer is "yes, probably".

If you want to persue further, pop down to the Discord and have a chat. https://pg3d-hax.uk/discord

Dave

**Comment by alinke** [comment]
thanks much Dave! Posted a note on the Discord
